;!knitout-2
;;Machine: SWG091N2
;;Gauge: 5
;;Width: 250
;;Carriers: 1 2 3 4 5 6 7 8 9 10
;;Position: Center
inhook  3 ;
tuck - f13 3 ; tuck loop -1, 
tuck - f11 3 ; tuck loop -1, 
tuck - f9 3 ; tuck loop -1, 
tuck - f7 3 ; tuck loop -1, 
tuck - f5 3 ; tuck loop -1, 
tuck - f3 3 ; tuck loop -1, 
tuck - f1 3 ; tuck loop -1, 
releasehook  3 ;
tuck + f2 3 ; tuck loop -1, odd cast-on
tuck + f4 3 ; tuck loop -1, 
tuck + f6 3 ; tuck loop -1, 
tuck + f8 3 ; tuck loop -1, 
tuck + f10 3 ; tuck loop -1, 
tuck + f12 3 ; tuck loop -1, 
knit - f13 3 ; knit loop -1, stabilize cast-on
knit - f12 3 ; knit loop -1, 
knit - f11 3 ; knit loop -1, 
knit - f10 3 ; knit loop -1, 
knit - f9 3 ; knit loop -1, 
knit - f8 3 ; knit loop -1, 
knit - f7 3 ; knit loop -1, 
knit - f6 3 ; knit loop -1, 
knit - f5 3 ; knit loop -1, 
knit - f4 3 ; knit loop -1, 
knit - f3 3 ; knit loop -1, 
knit - f2 3 ; knit loop -1, 
knit - f1 3 ; knit loop -1, 
knit + f1 3 ; knit loop 0, first row loops
knit + f2 3 ; knit loop 1, 
knit + f3 3 ; knit loop 2, 
knit + f4 3 ; knit loop 3, 
knit + f5 3 ; knit loop 4, 
knit + f6 3 ; knit loop 5, 
knit + f7 3 ; knit loop 6, 
knit + f8 3 ; knit loop 7, 
knit + f9 3 ; knit loop 8, 
knit + f10 3 ; knit loop 9, 
knit + f11 3 ; knit loop 10, 
knit + f12 3 ; knit loop 11, 
knit + f13 3 ; knit loop 12, 
xfer f3 b3 ;decrease negative-offsets to back
xfer f8 b8 ;
rack -1 ;rack to xfer b3 to f2
xfer b3 f2 ;decrease negative-offsets to front
xfer b8 f7 ;
rack 0 ;rack to xfer f6 to b6
xfer f6 b6 ;decrease positive-offsets to back
xfer f11 b11 ;
rack 1 ;rack to xfer b6 to f7
xfer b6 f7 ;decrease positive-offsets to front
xfer b11 f12 ;
rack 0 ;rack to xfer f4 to b4
xfer f4 b4 ;cables to back
xfer f5 b5 ;
xfer f9 b9 ;
xfer f10 b10 ;
rack -1 ;rack to xfer b10 to f9
xfer b10 f9 ;front -1 to front
rack 1 ;rack to xfer b4 to f5
xfer b4 f5 ;front 1 to front
xfer b9 f10 ;back 1 to front
rack -1 ;rack to xfer b5 to f4
xfer b5 f4 ;back -1 to front
knit - f13 3 ; knit loop 13, Knit course 1
knit - f12 3 ; knit loop 14, 
knit - f11 3 ; knit loop 15, 
knit - f10 3 ; knit loop 16, 
knit - f9 3 ; knit loop 17, 
knit - f8 3 ; knit loop 18, 
knit - f7 3 ; knit loop 19, 
knit - f6 3 ; knit loop 20, 
knit - f5 3 ; knit loop 21, 
knit - f4 3 ; knit loop 22, 
knit - f3 3 ; knit loop 23, 
knit - f2 3 ; knit loop 24, 
knit - f1 3 ; knit loop 25, 
knit + f1 3 ; knit loop 26, Knit course 2
knit + f2 3 ; knit loop 27, 
knit + f3 3 ; knit loop 28, 
knit + f4 3 ; knit loop 29, 
knit + f5 3 ; knit loop 30, 
knit + f6 3 ; knit loop 31, 
knit + f7 3 ; knit loop 32, 
knit + f8 3 ; knit loop 33, 
knit + f9 3 ; knit loop 34, 
knit + f10 3 ; knit loop 35, 
knit + f11 3 ; knit loop 36, 
knit + f12 3 ; knit loop 37, 
knit + f13 3 ; knit loop 38, 
outhook  3 ;
drop f1 ;Drop KnitGraph
drop f2 ;
drop f3 ;
drop f4 ;
drop f5 ;
drop f6 ;
drop f7 ;
drop f8 ;
drop f9 ;
drop f10 ;
drop f11 ;
drop f12 ;
drop f13 ;
